packages:
  - "packages/addon-indexeddb"
  - "packages/cli"
  - "packages/client"
  - "packages/crdt"
  - "packages/crdt-loro"
  - "packages/crdt-yjs"
  - "packages/eslint-config-pluv"
  - "packages/io"
  - "packages/persistence-cloudflare-transactional-storage"
  - "packages/persistence-redis"
  - "packages/platform-cloudflare"
  - "packages/platform-node"
  - "packages/platform-pluv"
  - "packages/pubsub-redis"
  - "packages/react"
  - "packages/tsconfig"
  - "packages/types"

  - "tests/e2e"
  - "tests/types"
allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  better-sqlite3: true
  core-js-pure: true
  esbuild: true
  prisma: set this to true or false
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@4.20260524.1'
