packages:
  - "apps/server-cloudflare"
  - "apps/storybook"
  - "apps/web"

  - "packages/cli"
  - "packages/client"
  - "packages/crdt-yjs"
  - "packages/eslint-config-pluv"
  - "packages/io"
  - "packages/persistance-redis"
  - "packages/platform-cloudflare"
  - "packages/platform-node"
  - "packages/pubsub-redis"
  - "packages/react"
  - "packages/tsconfig"
  - "packages/types"

  - "internal/cloudflare-utils"
  - "internal/rainfall"
  - "internal/react-chess"
  - "internal/react-hooks"
  - "internal/tailwind-config"

  - "tests/e2e"
