packages:
  - "apps/server-cloudflare"
  - "apps/storybook"
  - "apps/web"

  - "packages/addon-indexeddb"
  - "packages/cli"
  - "packages/client"
  - "packages/crdt"
  - "packages/crdt-loro"
  - "packages/crdt-yjs"
  - "packages/eslint-config-pluv"
  - "packages/io"
  - "packages/persistance-redis"
  - "packages/platform-cloudflare"
  - "packages/platform-node"
  - "packages/pubsub-redis"
  - "packages/react"
  - "packages/tsconfig"
  - "packages/types"

  - "internal/cloudflare-utils"
  - "internal/mdx-components"
  - "internal/rainfall"
  - "internal/react-chess"
  - "internal/react-code"
  - "internal/react-components"
  - "internal/react-hooks"
  - "internal/react-icons"
  - "internal/remark-plugins"
  - "internal/tailwind-config"
  - "internal/typings"
  - "internal/utils"

  - "tests/e2e"
