name = "server-cloudflare"
main = "src/index.ts"
compatibility_date = "2022-09-29"

[durable_objects]
bindings = [
	{ name = "rooms", class_name = "RoomDurableObject" },
]

[[migrations]]
tag = "v1"
new_classes = ["RoomDurableObject"]
