name = "pluv-server-prod"
main = "dist/index.js"
compatibility_date = "2023-04-08"

[durable_objects]
bindings = [
	{ name = "rooms", class_name = "RoomDurableObject" },
]

[[migrations]]
tag = "v1"
new_classes = ["RoomDurableObject"]
