name: Auto Assign
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]
permissions:
  issues: write
  pull-requests: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.0.1
