name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          addReviewers: true
          addAssignees: author
          reviewers: leedavidcs
          numberOfReviewers: 0
          skipKeywords: draft, wip
          excludeLabels: renovate
