name: Build Checks

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint
